### ISSUE TITLE
Config documentation

### ISSUE THREAD

**Issue by shayneoneill** [smacker/django-filebrowser-no-grappelli#12]
I'm a little bit lost on documentation here. There seems to be references to setting something called site.storage.location and site.directory, but all the documentation tells me is that I should set them.

I just for the life of me cant work out how.

I've put site.storage.location="<path>" in settings.py and it spits it out and tells me it doesnt know what site is. I've tried settings SITE_ID=1 and activating sites in django settings. No joy. Google doesnt seem to know, and I cant find any examples of how to configure this.

I'm sure the answer is in somebodies head , out there!

**Comment by smacker** [comment]
I didn't get what your problem is.

By default you can just create directory "uploads" in your MEDIA_ROOT.
If you want to change it - use FILEBROWSER_DIRECTORY in settings.py.

Don't forget to set MEDIA_ROOT&MEDIA_URL correctly. See https://docs.djangoproject.com/en/1.7/ref/settings/#media-root

For development you can serve files like this: https://docs.djangoproject.com/en/1.7/howto/static-files/#serving-files-uploaded-by-a-user-during-development
