### ISSUE TITLE
How much work is it tracking the upstream grappelli version?

### ISSUE THREAD

**Issue by andybak** [smacker/django-filebrowser-no-grappelli#16]
https://github.com/sehmaschine/django-filebrowser/issues/297

I don't use Grappelli but would prefer to submit patches to the upstream version. How feasible would it be to isolate the parts of each template that need to differ so that much more of the two codebases is identical?

**Comment by smacker** [comment]
Not so much. I do it for more than 4 years and know how to manage it).

About patches: You right! It's much better to submit patches to the upstream.
Because every change in this fork adds work on merging. Have a deal only with templates and css much easer then resolve python conflicts.

Right now, I think, it isn't possible to isolate templates on my side. We need some python changes (like add context to admin views, pass extra arguments and so on).
Also I still don't want to make breaking changes with older django versions. (I use django 1.4) But upstream now make improvements in 3.6.x branch that works only with Django 1.8.

**Comment by andybak** [comment]
Django 1.4 is now out of long term support. I would probably argue in favour of creating a final release that works on Django < 1.6 and not adding new features.

Do you plan on upgrading your sites soon? I'm going through the process at the moment if I can be of any assistance.

**Comment by smacker** [comment]
Yes, I plan to upgrade to 1.6 in next few months. But I think it'll need much more work to upgrade to 1.8. So I'll need to support 1.6 here. For now I don't know when I could drop everything below 1.8.

**Comment by andybak** [comment]
Could the mainstream branch of filebrowser-no-grappelli become 1.7/1.8 only but we keep a 1.6 branch and backport features to it that you personally need?

I understand this is probably just extra work for you but it seems a choice between that and stopping tracking upstream and this fork becoming frozen in time.

**Comment by andybak** [comment]
Just remembered this: https://github.com/arteria/django-compat

**Comment by smacker** [comment]
It won't be frozen. I already made it work with django 1.4-1.8. And will fetch last changes from upstream soon.

**Comment by smacker** [comment]
I updated fork to current upstream master. It should work for all versions of Django 1.4-1.9 now.
